CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR (100) NOT NULL,
    login VARCHAR (100) NOT NULL,
    name VARCHAR (100),
    birthday DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT,
    friend_id BIGINT,
    friendship_status BOOL,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (100) NOT NULL,
    description VARCHAR (200) NOT NULL,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_rating_id INT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id BIGINT,
    genre_id INT,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genres (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (40),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(5),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY (user_id, film_id)
);

ALTER TABLE friendship ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE friendship ADD FOREIGN KEY (friend_id) REFERENCES users (id);

ALTER TABLE films_likes ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE films_likes ADD FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE films ADD FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings (id);

ALTER TABLE films_genres ADD FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE films_genres ADD FOREIGN KEY (genre_id) REFERENCES genres (id);